apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: danchmpis/chm-k8s-namespace-backend
          ports:
            - containerPort: 8080
