apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: backend-svc
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend
