apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-deployment
  labels:
    app: deployment
    version: "1.0"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment
      version: "1.0"
  template:
    metadata:
      labels:
        app: deployment
        version: "1.0"
    spec:
      containers:
      - name: old-deployment
        image: hashicorp/http-echo
        args:
          - "-text=version: 1.0"
        ports:
          - containerPort: 5678